spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/systemcommerce}
    username: ${DATABASE_USERNAME:systemcommerce}
    password: ${DATABASE_PASSWORD:systemcommerce}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.flywaydb: INFO
    org.springframework.security: INFO
